export const INITIAL_MENU = [
  { category: "PEIXES", name: "Pratiqueira", price: 60.00, description: "Acompanha arroz, farofa e vinagrete" },
  { category: "PEIXES", name: "Pescadinha (3 unidades grandes)", price: 75.00, description: "Acompanha arroz, farofa e vinagrete" },
  { category: "PEIXES", name: "Pescadinha (6 unidades pequenas)", price: 70.00, description: "Acompanha arroz, farofa e vinagrete" },
  { category: "PEIXES", name: "Filé de Pescada Adoré", price: 85.00, description: "Acompanha arroz, farofa e feijão" },
  { category: "PEIXES", name: "Filé de Pescada Adoré com Fritas", price: 100.00, description: "Acompanha arroz, farofa e feijão" },
  { category: "PEIXES", name: "Filé de Pescada na Chapa com Fritas", price: 110.00, description: "Acompanha arroz, farofa e feijão" },
  { category: "PEIXES", name: "Isca de Peixe", price: 70.00, description: "Acompanha farofa e molho rosê" },
  { category: "PEIXES", name: "Isca com Fritas", price: 80.00, description: "Acompanha farofa e molho rosê" },
  { category: "PEIXES", name: "Isca com Fritas Completa", price: 90.00, description: "Acompanha arroz, farofa e feijão" },
  { category: "PEIXES", name: "Camarão ao Alho e Óleo", price: 90.00, description: "Acompanha farofa" },
  { category: "PEIXES", name: "Camarão à Milanesa", price: 100.00, description: "Acompanha arroz e farofa" },
  { category: "PEIXES", name: "Camarão à Milanesa Completo", price: 130.00, description: "Acompanha arroz, farofa e fritas" },
  { category: "PEIXES", name: "Caranguejo Toc-Toc", price: 60.00, description: "Acompanha farofa e vinagrete" },
  { category: "PEIXES", name: "Enchova Corvina Pequena", price: 150.00 },
  { category: "PEIXES", name: "Enchova Corvina Média", price: 180.00 },
  { category: "PEIXES", name: "Enchova Corvina Grande", price: 200.00 },
  { category: "PEIXES", name: "Pratiqueira Simples", price: 50.00, description: "Acompanha farofa e vinagrete" },
  { category: "PEIXES", name: "Pescadinha Completa", price: 100.00, description: "Acompanha arroz, feijão, farofa e vinagrete" },
  
  { category: "CARNES", name: "Filé de Carne na Chapa", price: 100.00, description: "Acompanha arroz, feijão e farofa" },
  { category: "CARNES", name: "Filé de Carne na Chapa com Fritas", price: 110.00, description: "Acompanha arroz e farofa" },
  { category: "CARNES", name: "Filé de Carne na Chapa a Cavalo", price: 120.00, description: "Acompanha fritas, arroz, farofa e feijão" },
  { category: "CARNES", name: "Bife a Cavalo", price: 90.00, description: "Acompanha fritas, arroz, farofa e feijão" },
  { category: "CARNES", name: "Bife Acebolado", price: 80.00, description: "Acompanha arroz, feijão e farofa" },
  { category: "CARNES", name: "Frango na Chapa", price: 70.00, description: "Acompanha arroz, feijão e farofa" },
  { category: "CARNES", name: "Frango na Chapa com Fritas", price: 75.00, description: "Acompanha arroz, feijão e farofa" },
  { category: "CARNES", name: "Chapa Mista", price: 170.00, description: "Carne, Frango, Peixe e Camarão - Acompanha arroz, feijão, farofa e batata frita" },
  
  { category: "PORÇÕES", name: "Arroz", price: 7.00 },
  { category: "PORÇÕES", name: "Farofa", price: 7.00 },
  { category: "PORÇÕES", name: "Vinagrete", price: 7.00 },
  { category: "PORÇÕES", name: "Feijão", price: 7.00 },
  
  { category: "TIRA GOSTO", name: "Macaxeira", price: 30.00, description: "com molho rosê" },
  { category: "TIRA GOSTO", name: "Batata frita", price: 30.00, description: "com molho rosê" },
  { category: "TIRA GOSTO", name: "Calabresa com farofa", price: 50.00 },
  { category: "TIRA GOSTO", name: "Filé a palito com farofa", price: 100.00 },
  
  { category: "BEBIDAS", name: "Skol 600 ml", price: 13.00 },
  { category: "BEBIDAS", name: "Brahma 600 ml", price: 13.00 },
  { category: "BEBIDAS", name: "Tijuca 600 ml", price: 13.00 },
  { category: "BEBIDAS", name: "Cerveja Long Neck", price: 15.00 },
  { category: "BEBIDAS", name: "Refrigerante lata", price: 7.00 },
  { category: "BEBIDAS", name: "Refrigerante 1L", price: 10.00 },
  { category: "BEBIDAS", name: "Coca-Cola 2L", price: 18.00 },
  { category: "BEBIDAS", name: "Guaraná 2L", price: 18.00 },
  { category: "BEBIDAS", name: "Água Mineral 350 ml", price: 3.00 },
  { category: "BEBIDAS", name: "Água Mineral 500 ml", price: 5.00 },
  { category: "BEBIDAS", name: "Água Mineral 1,5L", price: 10.00 }
];
